sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.npm"
install:
- npm ci 
script:
- npm run lint
- npm run start
- npm run build
- npm test
- npm run coveralls
